"""Create base dicts models

Revision ID: 4e411e35bab5
Revises: 62e789ad3ba5
Create Date: 2022-11-28 14:00:31.111019

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4e411e35bab5'
down_revision = '62e789ad3ba5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_types',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('slug'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('countries',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('slug'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('genres',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('slug'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genres')
    op.drop_table('countries')
    op.drop_table('book_types')
    # ### end Alembic commands ###
