"""First migration

Revision ID: 62e789ad3ba5
Revises: 
Create Date: 2022-11-28 13:50:11.339541

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '62e789ad3ba5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
